services:
  - type: web
    name: credit-risk-api
    env: image
    plan: free
    region: oregon
    image:
      url: ghcr.io/amarjeetjha17/mlops-credit-risk-system:latest
    envVars:
      - key: PORT
        value: "8000"
